theme = "emacs"

[editor]
end-of-line-diagnostics = "hint"
line-number = "relative"
true-color = true
cursorline = true
scrolloff = 12

[editor.inline-diagnostics]
cursor-line = "error"

[editor.whitespace]
render = { space = "all", tab = "all", newline = "none" }

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true
skip-levels = 1
